### ISSUE TITLE
Option to exclude authors from autopage generation

### ISSUE THREAD

**Issue by gouravkhunger** [gouravkhunger/jekyll-auto-authors#1]
It'd be nice to have an exclude option to not render auto-pages for specific author usernames from the data file. In some specific scenarios it could be important to have author data while not processing an author page.

For example, for author data:

```yml
john:
  name: 'User 1'
  bio: 'Bio of user 1'
  website: 'http://user1.com'

jane:
  name: 'User 2'
  bio: 'Bio of user 2'
  website: 'http://user2.com'
```

there could be an `exclude` directive for author autopages config block, to skip autopage generation for an array of usernames:

```yml
autopages:

  # Other autopage configs

  authors:
    enabled: true
    data: '_data/authors.yml' # Data file with the author details

    exclude: ["jane"] # does not process auto page for author jane

    # Other author autopage configs
```

---

To consider: Besides an exclude directive for an array of usernames in the `_config.yml`, would it be nice to have an `exclude: true` option for specific author data blocks inside the data file itself?
